name: cuidapet_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.1.0
  shelf: ^1.1.2
  shelf_router: ^1.0.0
  shelf_router_generator: ^1.0.0
  dotenv: ^3.0.0-nullsafety.0
  mysql1: ^0.19.2
  get_it: ^7.1.3
  logger: ^1.0.0
  injectable: ^1.4.0
  injectable_generator: ^1.4.0
  build_runner: ^2.0.2

dev_dependencies:
  pedantic: ^1.9.0
